Add gitflow enforcer

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -5,21 +5,22 @@ permissions:
   contents: read
 
 on:
-  push:
-    branches:
-      - main
-      - dev
-      - production
   pull_request:
-    branches:
-      - main
-      - dev
-      - production
-    types: [ opened, reopened, edited, synchronize ]
+    types: [opened, reopened, edited, synchronize]
 
 jobs:
+  gitflow_enforcer:
+    name: Enforce GitFlow 👮🏻‍
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.base_ref == 'main' && github.head_ref != 'dev' || github.base_ref == 'production' && github.head_ref != 'main'
+        run: |
+          echo "ERROR: You can only merge to main from dev and to production from main"
+          exit 1
   define-environment:
     name: Set ✨ environment ✨ based on the branch 🌳
+    needs: gitflow_enforcer
     runs-on: ubuntu-latest
     steps:
       - name: Set the environment
